param_definitions = {
    "LENG": {
        "Name": "Pattern Length/Last",
        "TYPE": "INT",
        "RANGE": (1, 64),
        "DEFAULT": 16,
    },
    "SCALE": {
        "Name": "Pattern Scale (Step Length)",
        "TYPE": "DICT",
        "VALUES": {
            "0": "1_8",
            "1": "1_16",
            "2": "1_32",
            "3": "8t",
            "4": "16t",
            "5": "32t",
        },
        "DEFAULT": "1",
    },
    "TRANSPOSE": {
        "Name": "Key Transpose",
        "TYPE": "INT",
        "RANGE": (-60, 60),
        "DEFAULT": 0,
    },
    "LEVEL": {"Name": "Overall Volume", "TYPE": "INT", "RANGE": (0, 127), "DEFAULT": 70},
    # Tempo is multiplied by 100
    "TEMPO": {
        "Name": "Tempo",
        "TYPE": "DIV100",
        "RANGE": (400, 30000),
        "DEFAULT": 10000,
    },
    "SHUFFLE": {"Name": "Shuffle", "TYPE": "INT", "RANGE": (-90, 90), "DEFAULT": 0},
    "ARP_TYPE": {
        "Name": "Arp Type",
        "TYPE": "DICT",
        "VALUES": {
            "0": "OFF",
            "1": "UP",
            "2": "doWn",
            "3": "UP.dW",
            "4": "UP.2",
            "5": "dW.2",
            "6": "U.d.2",
            "7": "rand",
            "8": "rnd.2",
        },
        "DEFAULT": "0",
    },
    "ARP_RATE": {
        "Name": "Arp Rate",
        "TYPE": "DICT",
        "VALUES": {
            "0": "1_4",
            "1": "1_8",
            "2": "1_16",
            "3": "1_32",
            "4": "8t",
            "5": "16t",
            "6": "32t",
        },
        "DEFAULT": "2",
    },
    "MOTION_CC1": {"Name": "Motion Control 1", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC2": {"Name": "Motion Control 2", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC3": {"Name": "Motion Control 3", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC4": {"Name": "Motion Control 4", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC5": {"Name": "Motion Control 5", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC6": {"Name": "Motion Control 6", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC7": {"Name": "Motion Control 7", "TYPE": "UNK", "DEFAULT": "-1"},
    "MOTION_CC8": {"Name": "Motion Control 8", "TYPE": "UNK", "DEFAULT": "-1"},
    # This depends on LFO_SYNC. How do we represent a RANGE vs a DICT?
    "LFO_RATE": {
        "Name": "LFO Rate",
        "TYPE": "DICT",
        "VALUES": {
            "0": "8_1",
            "1": "6_1",
            "2": "8_1t",
            "3": "4_1",
            "4": "3_1",
            "5": "4_1t",
            "6": "2_1",
            "7": "1d",
            "8": "2_1t",
            "9": "1_1",
            "10": "2d",
            "11": "1t",
            "12": "1_2",
            "13": "4d",
            "14": "2t",
            "15": "1_4",
            "16": "8d",
            "17": "4t",
            "18": "1_8",
            "19": "16d",
            "20": "8t",
            "21": "1_16",
            "22": "32d",
            "23": "16t",
            "24": "1_32",
            "25": "64d",
            "26": "32t",
            "27": "1_64",
            "28": "128d",
            "29": "64t",
            "30": "128",
        },
        "DEFAULT": 120,
    },
    "LFO_WAVE_FORM": {
        "Name": "LFO Waveform",
        "TYPE": "DICT",
        "VALUES": {
            "0": "Rising Saw",
            "1": "Descending Saw",
            "2": "Triangle",
            "3": "Square",
            "4": "Random ",
            "5": "Noise",
        },
        "DEFAULT": "2",
    },
    "VCO_MOD_DEPTH": {
        "Name": "Oscillator LFO",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },  # Depends on PWM Source
    "VCO_RANGE": {
        "Name": "Oscillator Octave",
        "TYPE": "DICT",
        "VALUES": {"0": "64'", "1": "32'", "2": "16'", "3": "8'", "4": "4'", "5": "2'"},
        "DEFAULT": "",
    },
    "VCO_PULSE_WIDTH": {
        "Name": "Oscillator Pulse Width",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "VCO_PWM_SOURCE": {
        "Name": "Oscillator PWM Source",
        "TYPE": "DICT",
        "VALUES": {"0": "Envelope", "1": "Manual", "2": "LFO", "DEFAULT": ""},
    },
    "VCO_PWM_LEVEL": {
        "Name": "Oscillator PWM Level",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 255,
    },
    "VCO_SAW_LEVEL": {
        "Name": "Oscillator Saw Level",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCO_SUB_LEVEL": {
        "Name": "Oscillator Sub Level",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCO_SUB_TYPE": {
        "Name": "Oscillator Sub Octave",
        "TYPE": "DICT",
        "VALUES": {"0": "-2(A)", "1": "-2(S)", "2": "-1"},
        "DEFAULT": "2",
    },
    "VCO_NOISE_LEVEL": {
        "Name": "Oscillator Noise Level",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCF_CUTOFF": {
        "Name": "Filter Cutoff",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "VCF_RESONANCE": {"Name": "Filter Resonance", "DEFAULT": ""},
    "VCF_ENV_DEPTH": {
        "Name": "Filter Envelope Depth",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCF_MOD_DEPTH": {
        "Name": "Filter LFO Depth",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCF_KEY_FOLLOW": {
        "Name": "Filter Keyboard Follow",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 0,
    },
    "VCA_ENV_MODE": {"Name": "Filter Envelope Mode", "DEFAULT": ""},
    "ENV_TRG_MODE": {"Name": "Filter Trigger Mode", "DEFAULT": ""},
    "ENV_ATTACK": {
        "Name": "Envelope Attack",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "ENV_DECAY": {
        "Name": "Envelope Decay",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "ENV_SUSTAIN": {
        "Name": "Envelope Sustain",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "ENV_RELEASE": {
        "Name": "Envelope Release",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": "",
    },
    "ASSIGN_MODE": {"Name": "Assign Mode", "TYPE": "UNK", "DEFAULT": "2"},  # ???
    "CHORD_VOICE2_SW": {
        "Name": "Chord Voice 2 Switch",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "On"},
        "DEFAULT": "1",
    },
    "CHORD_VOICE3_SW": {
        "Name": "Chord Voice 3 Switch",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "On"},
        "DEFAULT": "1",
    },
    "CHORD_VOICE4_SW": {
        "Name": "Chord Voice 4 Switch",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "On"},
        "DEFAULT": "1",
    },
    "CHORD_VOICE2_KEY_SHIFT": {
        "Name": "Chord Voice 2 Shift",
        "TYPE": "INT",
        "RANGE": (-12, 12),
        "DEFAULT": "12",
    },
    "CHORD_VOICE3_KEY_SHIFT": {
        "Name": "Chord Voice 3 Shift",
        "TYPE": "INT",
        "RANGE": (-12, 12),
        "DEFAULT": "7",
    },
    "CHORD_VOICE4_KEY_SHIFT": {
        "Name": "Chord Voice 4 Shift",
        "TYPE": "INT",
        "RANGE": (-12, 12),
        "DEFAULT": "5",
    },
    "VCO_BEND_SENS": {"Name": "Oscillator Bend Sensitivity", "DEFAULT": ""},
    "VCF_BEND_SENS": {"Name": "Filter Bend Sensitivity", "DEFAULT": ""},
    "LFO_MOD_DEPTH": {"Name": "LFO Modulation Depth", "DEFAULT": ""},
    "PORTAMENTO_MODE": {"Name": "Portamento Mode", "DEFAULT": ""},
    "PORTAMENTO_TIME": {"Name": "Portamento Time", "DEFAULT": ""},
    "NOISE_MODE": {
        "Name": "Noise Mode",
        "TYPE": "DICT",
        "VALUES": {"0": "Pink", "1": "White"},
        "DEFAULT": "0",
    },
    "LFO_MODE": {"Name": "LFO Mode", "DEFAULT": ""},
    "FINE_TUNE": {"Name": "Fine Tune", "DEFAULT": ""},
    "TEMPO_SYNC": {"Name": "Tempo Sync", "DEFAULT": ""},
    "CHORUS": {"Name": "Chorus", "DEFAULT": ""},
    "DELAY_LEVEL": {"Name": "Delay Level", "DEFAULT": ""},
    "DELAY_TIME": {"Name": "Delay Time", "DEFAULT": ""},
    "DELAY_TEMPO": {"Name": "Delay Tempo", "DEFAULT": ""},
    "DELAY_FEEDBACK": {"Name": "Delay Feedback", "DEFAULT": ""},
    "DELAY_LOW_CUT": {"Name": "Delay Low-Cut", "DEFAULT": ""},
    "DELAY_HIGH_CUT": {"Name": "Delay Hight-Cut", "DEFAULT": ""},
    "DELAY_SW": {"Name": "Delay Switch", "DEFAULT": ""},
    "REVERB_TYPE": {"Name": "Reverb Type", "DEFAULT": ""},
    "REVERB_TIME": {"Name": "Reverb Time", "DEFAULT": ""},
    "REVERB_LEVEL": {"Name": "Reverb Level", "DEFAULT": ""},
    "REVERB_PRE_DELAY": {"Name": "Reverb Pre-Delay", "DEFAULT": ""},
    "REVERB_LOW_CUT": {"Name": "Reverb Low-Cut", "DEFAULT": ""},
    "REVERB_HIGH_CUT": {"Name": "Reverb High-Cut", "DEFAULT": ""},
    "REVERB_DENSITY": {"Name": "Reverb Density", "DEFAULT": ""},
    "OSC_DRAW_SW": {
        "Name": "Oscillator Draw Switch",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "Step", 2: "Slope"},
        "DEFAULT": "0",
    },
    "OSC_DRAW_MULT": {
        "Name": "Oscillator Draw Multiplier",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 7,
    },  # Encoding?
    # Oscillator Draw Pads SPLIT_TC: Binary representation split in 2 halves, then 'Two's Complement' each into an integer
    "OSC_DRAW_P1": {
        "Name": "Oscillator Draw 1/2",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 46492,
    },
    "OSC_DRAW_P2": {
        "Name": "Oscillator Draw 3/4",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 59342,
    },
    "OSC_DRAW_P3": {
        "Name": "Oscillator Draw 5/6",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 6400,
    },
    "OSC_DRAW_P4": {
        "Name": "Oscillator Draw 7/8",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 19250,
    },
    "OSC_DRAW_P5": {
        "Name": "Oscillator Draw 9/10",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 19300,
    },
    "OSC_DRAW_P6": {
        "Name": "Oscillator Draw 11/12",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 6450,
    },
    "OSC_DRAW_P7": {
        "Name": "Oscillator Draw 13/14",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 59136,
    },
    "OSC_DRAW_P8": {
        "Name": "Oscillator Draw 15/16",
        "TYPE": "SPLIT_TC",
        "INT": (0, 65535),
        "DEFAULT": 46542,
    },
    "OSC_CHOP_TYPE": {"Name": "Oscillator Chop Type", "DEFAULT": "0"},  # ???
    "OSC_CHOP_OVERTONE": {
        "Name": "Oscillator Chop Overtone",
        "TYPE": "INT",
        "RANGE": (0, 200),
        "DEFAULT": "",
    },
    "OSC_CHOP_COMB_TYPE": {"Name": "Oscillator Chop Comb Type", "DEFAULT": "0"},
    "OSC_CHOP_COMB": {
        "Name": "Oscillator Chop Comb",
        "TYPE": "INT",
        "RANGE": (0, 255),
        "DEFAULT": 7,
    },  # Encoding??
    # The number in binary _reversed_ represents the on/off pattern of the pads
    "OSC_CHOP_PWM": {
        "Name": "Oscillator Chop Square Pattern",
        "TYPE": "INT",
        "RANGE": (0, 65535),
        "DEFAULT": 65535,
    },
    "OSC_CHOP_SAW": {
        "Name": "Oscillator Chop Saw Pattern",
        "TYPE": "INT",
        "RANGE": (0, 65535),
        "DEFAULT": 65535,
    },
    "OSC_CHOP_SUB": {
        "Name": "Oscillator Chop Sub Pattern",
        "TYPE": "INT",
        "RANGE": (0, 65535),
        "DEFAULT": 65535,
    },
    "OSC_CHOP_NOISE": {
        "Name": "Oscillator Chop Noise Pattern",
        "TYPE": "INT",
        "RANGE": (0, 65535),
        "DEFAULT": 65535,
    },
    "RISER_MODE": {"Name": "Riser Mode", "DEFAULT": ""},
    "RISER_SW": {"Name": "Riser Switch", "DEFAULT": ""},
    "RISER_CTRL": {"Name": "Riser Control", "DEFAULT": ""},
    "RISER_BEAT": {"Name": "Riser Beat", "DEFAULT": ""},
    "RISER_RESO": {"Name": "Riser Resonance", "DEFAULT": ""},
    "RISER_LEVEL": {"Name": "Riser Level", "DEFAULT": ""},
    "DM_ASSIGN_X": {"Name": "D-Motion Assign X", "TYPE": "UNK", "DEFAULT": "5"},
    "DM_ASSIGN_Y": {"Name": "D-Motion Assign Y", "TYPE": "UNK", "DEFAULT": "6"},
    "DM_ASSIGN_TAP": {"Name": "D-Motion Assign Tap", "TYPE": "UNK", "DEFAULT": "0"},
    "DM_ASSIGN_FF": {"Name": "D-Motion Assign FF", "TYPE": "UNK", "DEFAULT": "0"},
    "DM_SENS_X": {"Name": "D-Motion X Sensitivity", "TYPE": "UNK", "DEFAULT": "5"},
    "DM_SENS_Y": {"Name": "D-Motion Y Sensitivity", "TYPE": "UNK", "DEFAULT": "5"},
    "LFO_KEY_TRIG": {
        "Name": "LFO Key Trigger",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "On"},
        "DEFAULT": "0",
    },
    "LFO_SYNC": {
        "Name": "LFO Sync Mode",
        "TYPE": "DICT",
        "VALUES": {"0": "Off", "1": "On"},
        "DEFAULT": "0",
    },
    "RISER_SHAPE": {"Name": "Riser Shape", "DEFAULT": ""},
    "PRM1": {"Name": "PRM 1", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM2": {"Name": "PRM 2", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM3": {"Name": "PRM 3", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM4": {"Name": "PRM 4", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM5": {"Name": "PRM 5", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM6": {"Name": "PRM 6", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM7": {"Name": "PRM 7", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM8": {"Name": "PRM 8", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM9": {"Name": "PRM 9", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM10": {"Name": "PRM 10", "TYPE": "UNK", "DEFAULT": "0"},
    "PRM11": {"Name": "PRM 11", "TYPE": "UNK", "DEFAULT": "0"},
}
